# Generated by Django 5.2.17 on 2026-09-23 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvs', '0002_cv_git_url_cv_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveBigIntegerField()),
                ('posted_at', models.DateTimeField()),
                ('source_text', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unactionable', 'Unactionable'), ('below_threshold', 'Below Threshold'), ('ready', 'Ready'), ('applying', 'Applying'), ('applied', 'Applied'), ('needs_review', 'Needs Review')], max_length=24)),
                ('attempt_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvs.cv')),
            ],
            options={
                'db_table': 'opportunities',
                'ordering': ('-posted_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('message_id', 'url'), name='unique_post_url')],
            },
        ),
    ]
