# Generated by Django 5.2.17 on 2026-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source_links',
            field=models.JSONField(default=list),
        ),
    ]
