# Generated by Django 5.2.17 on 2026-09-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='git_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
